site_name: 芜草初伸记
site_url: https://yulljie.github.io/CattleEatsGrass
theme:
  name: material
  language: zh
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - footnotes
  
# Repository
repo_name: Yulljie169/CattleEatsGrassDev
repo_url: https://github.com/Yulljie169/CattleEatsGrassDev

extra_css:
  - stylesheets/extra.css
