site_name: 芜草初伸记
site_url: https://yulljie169.github.io/CattleEatsGrassDev
theme:
  name: material
  language: zh
markdown_extensions:
  - footnotes
  
# Repository
repo_name: Yulljie169/CattleEatsGrassDev
repo_url: https://github.com/Yulljie169/CattleEatsGrassDev

extra_css:
  - stylesheets/extra.css
